language: node_js
node_js:
  - "stable"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

services:
  - postgresql

before_script:
  # - createdb mai_sms_test
  - yarn migrate:test
  - yarn install

script:
  - yarn test

addons:
  postgresql: "9.3"
